### ISSUE TITLE
Hi, Simon

### ISSUE THREAD

**Issue by GrCOTE7** [SimonDevelop/slim-doctrine#1]
Un dépôt ma foi fort intéressant et novateur :-)...

Juste, bien qu'il n'ait que qqes mois d'ancienneté, les librairies gulp ne se chargent pas (plus ?) automatiquement...

Pas hyper dramatique, il suffit de les charger 'à la main' une à une, puis ton app semble tourner parfaitement (y) !

Super boulot :-) !

Et donc, juste, penses-tu mettre à jour ce dépôt :-) ?

**Comment by SimonDevelop** [comment]
Désolé pour ma réponse tardive, merci du compliment et oui je tiens à mettre ce dépot à jour, je m'en sert pour certains de mes projets.

Si tu repères des problèmes comme celui-là, hésite pas à faire une issue voir un fork pour ensuite faire une pull request ;)

Sans oublié des idées d'ajout de librairies, en ce moment je réfléchi encore pour un formBuilder, mais je suis pas fan et je préfère laisser la liberté aux développeurs d'en ajouter un ou non.
